---

- name: AutoUpdate
  hosts: all
  become: true
  roles:
    - weareinteractive.apt
  vars:
    apt_cache_valid_time: 7200
    apt_packages:
      - python3
      - caddy
    apt_unattended_upgrades_notify_error_only: false
    apt_remove_recommends: true
    apt_remove_suggests: true
    apt_remove_purge: true
