---
- name: Update Root CA
  hosts: all
  tasks:
    - name: Make sure the folder exists (Debian, Ubuntu)
      ansible.builtin.file:
        path: /usr/local/share/ca-certificates
        state: directory
        mode: "0755"

  # Note that the .crt is actually a .pem renamed
    - name: Copy Root CA
      ansible.builtin.get_url:
        url: "https://bucket.glencook.tech/root_ca.crt"
        dest: "/usr/local/share/ca-certificates/glencooktech.crt"
        mode: "0755"

    - name: Copy Intermediate CA
      ansible.builtin.get_url:
        url: "https://bucket.glencook.tech/intermediate_ca.crt"
        dest: "/usr/local/share/ca-certificates/glencooktech-intermediate.crt"
        mode: "0755"
    - name: Update CA Trust (Debian, Ubuntu)
      ansible.builtin.command: update-ca-certificates
