---
- name: Common packages
  ansible.builtin.package:
    name: zsh
    state: present

- name: Add Ansible admin user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash

- name: Add glen user
  ansible.builtin.user:
    name: glen
    comment: Glen Cook
    shell: /usr/bin/zsh

- name: "Set authorized key taken from file"
  ansible.posix.authorized_key:
    user: ansible
    exclusive: true
    state: present
    key: "{{ lookup('url', 'https://pub-e89ede954fc048a7824791610744dbdb.r2.dev/ansible.pub') }}"

- name: "Add authorized keys"
  ansible.posix.authorized_key:
    user: glen
    exclusive: true
    state: present
    key: "{{ lookup('url', 'https://pub-e89ede954fc048a7824791610744dbdb.r2.dev/primary.pub') }}"

- name: "Allow glen Sudo"
  community.general.sudoers:
    name: glen
    state: present
    user: glen
    commands: ALL

- name: "Allow ansible Sudo"
  community.general.sudoers:
    name: ansible
    state: present
    user: ansible
    commands: ALL

- name: "Install the correct web server for RHEL"
  ansible.builtin.import_tasks: redhat.yaml
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Run Ubuntu Tasks"
  ansible.builtin.import_tasks: ubuntu.yaml
  when: ansible_facts['os_family'] == 'Debian'
