- name: Common packages
  ansible.builtin.package:
    name: zsh
    state: present

- name: Add Ansible admin user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash

- name: Add cookytime user
  ansible.builtin.user:
    name: cookytime
    comment: Glen Cook
    shell: /usr/bin/zsh

- name: "Set authorized key taken from file"
  ansible.posix.authorized_key.authorized_key:
    user: ansible
    exclusive: true
    state: present
    key: "{{ lookup('url', 'https://glencooktechpublickeys.blob.core.windows.net/publicssh/ansible.pub') }}"

- name: "Add authorized keys"
  ansible.posix.authorized_key:
    user: cookytime
    exclusive: true
    state: present
    key: "{{ lookup('url', 'https://glencooktechpublickeys.blob.core.windows.net/publicssh/primary.pub') }}"

- name: "Allow Cookytime Sudo"
  community.general.sudoers:
    name: cookytime
    state: present
    user: cookytime
    commands: ALL

- name: "Allow ansible Sudo"
  community.general.sudoers:
    name: ansible
    state: present
    user: ansible
    commands: ALL

- name: "Install the correct web server for RHEL"
  ansible.builtin.import_tasks: redhat.yaml
  when: ansible_facts['os_family'] == 'RedHat'

- name: "Run Ubuntu Tasks"
  ansible.builtin.import_tasks: ubuntu.yaml
  when: ansible_facts['os_family'] == 'Debian'
