---
- name: Collect facts
  ansible.builtin.setup:

- name: Ensure base groups exists
  ansible.builtin.group:
    name: "{{ item }}" 
    state: present
  with_items:
     - docker
     - libvirt
     - frr

- name: Add Ansible admin user
  ansible.builtin.user:
    name: ansible
    shell: /bin/bash
    groups: docker,libvirt,frr

- name: Add sudo ansible
  community.general.sudoers:
    name: ansible
    state: present
    user: ansible
    commands: ALL

- name: Set authorized key taken from file
  ansible.posix.authorized_key.authorized_key:
    user: ansible
    state: present
    key: "{{ lookup('url', 'https://stuff.beastcave.net/keys/ansible.keys') }}"

- name: Add cookytime user
  ansible.builtin.user:
    name: cookytime
    comment: Glen Cook
    groups: docker,libvirt,frr

- name: "Add authorized keys"
  ansible.posix.authorized_key:
    user: cookytime
    key: "{{ lookup('url', 'https://stuff.beastcave.net/keys/cookytime.keys') }}"

- name: Add sudo cookytime
  community.general.sudoers:
    name: cookytime
    state: present
    user: cookytime
    commands: ALL

- name: Install the correct web server for RHEL
  import_tasks: redhat.yaml
  when: ansible_facts['os_family']|lower == 'redhat'
